void six(const char *str);
void show();
void name();
void total();
void lvlshow();
void xpshow();
void nxtxpshow();
void addcoin(int data);
void con();
void t();
void x();
void y();
void d();
void resetmine();
void reset(int data);
void lvlstore(int data);
void nxtxp(int data);
void mineadd(int data);
void xpstore(int data);
void ironshow();
void coalshow();
void silvershow();
void crimshow();
void mythanshow();
void goldshow();
void magicshow();
void minexshow();
void xpboostshow();
void coal(int data);
void iron(int data);
void silver(int data);
void crim(int data);
void mythan(int data);
void gold(int data); 
void magic(int data);
void minexadd(int data);
void xpboostadd(int data);
